services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 3000:3000

  postgres:
    image: postgres:14
    container_name: golf-tee-times-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tee_times_pg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
