name: Build and Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image with datetime tag
        run: |
          IMAGE_TAG="tapontikes/golf-ri.com:$(date +'%Y-%m-%d_%H-%M-%S')"
          docker build . --file Dockerfile --tag $IMAGE_TAG
          docker tag $IMAGE_TAG tapontikes/golf-ri.com:latest

      - name: Push the Docker image
        run: |
          DATETIME_TAG=$(date +'%Y-%m-%d_%H-%M-%S')
          IMAGE_TAG="tapontikes/golf-ri.com:$DATETIME_TAG"
          docker push $IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy the Docker Compose stack
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER_IP }} << 'EOF'
          cd /home/tom/ri-tee-times/
          
          DATETIME_TAG=$(date +'%Y-%m-%d_%H-%M-%S')
          docker pull tapontikes/golf-ri.com:$DATETIME_TAG
          docker tag tapontikes/golf-ri.com:$DATETIME_TAG tapontikes/golf-ri.com:latest
          
          # Stop and remove the old app container (but keep the PostgreSQL container running)
          docker stop ri-tee-times-app-1          
          docker rm ri-tee-times-app-1
          docker image prune -f
          
          # Restart the application container with the new image
          docker-compose up -d app
          
          EOF
