name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        IMAGE_TAG=tapontikes/golf-ri.com:latest
        docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Push the Docker image
      run: |
        IMAGE_TAG=tapontikes/golf-ri.com:latest
        docker push $IMAGE_TAG
